# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20170406_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='used',
        ),
    ]
